= Kaadin
Nicolas Fränkel <nicolas@frankel.ch>
:lang: en
:source-highlighter: highlight.js
:sourcedir: kaadin-sampler/src/main/kotlin/ch/frankel/kaadin
:sectnums:
:toc: macro
:experimental:

Kaadin is a library to create link:https://vaadin.com/[Vaadin] Graphical User Interface using a link:https://kotlinlang.org/[Kotlin] Domain-Specific Language .

[NOTE]
====
At the moment, Kaadin is a _work in progress_. Contributions are always welcome.
====

toc::[]

== Two-minutes tutorial

In order to directly start using Kaadin, follow the next steps:

1. Import the namespace `ch.frankel.kaadin.*`
1. There's one Kaadin function for each Vaadin component _e.g._ `button()` maps `Button()`
1. In `UI.init()`, call the parent component function, it will automatically be added as the `UI` content
1. Use nested block to add and configure components

Here's a sample displaying a label inside a vertical layout:

[source,kotlin]
----
include::{sourceDir}/doc/SimpleUsageUI.kt[tags=simpleusageui]
----

== User manual

The best user manual is a link:{sourceDir}/sammpler/KaadinSampler.kt[sampler] demoing usage of each function.

It's a full-fledged Vaadin application so it can be run either inside your own servlet-container (3.0+) or directly from the command-line:

[source,bash]
----
mvn install
cd kaadin-sampler
mvn package org.apache.tomcat.maven:tomcat7-maven-plugin:run
----

== Available components

Please refer to the link:Components.adoc[components list].

== License

Kaadin is distributed under the friendly link:LICENSE[Apache 2.0 License].

